import {
  Baby,
  Banknote,
  Book,
  Briefcase,
  Building2,
  Bus,
  Car,
  Clapperboard,
  Coffee,
  Coins,
  CreditCard,
  Dumbbell,
  Fuel,
  Gamepad2,
  Gem,
  Gift,
  GraduationCap,
  HandCoins,
  HeartPulse,
  House,
  Landmark,
  Laptop,
  Music,
  Package,
  PawPrint,
  PiggyBank,
  Pill,
  Plane,
  Receipt,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Tag,
  TrendingUp,
  Utensils,
  Wallet,
  Wifi,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

/** Curated set offered in the icon picker. Keys are what gets stored on a category. */
export const CATEGORY_ICONS: Record<string, LucideIcon> = {
  utensils: Utensils,
  cart: ShoppingCart,
  coffee: Coffee,
  car: Car,
  fuel: Fuel,
  bus: Bus,
  plane: Plane,
  "shopping-bag": ShoppingBag,
  shirt: Shirt,
  gem: Gem,
  house: House,
  building: Building2,
  zap: Zap,
  wifi: Wifi,
  smartphone: Smartphone,
  receipt: Receipt,
  clapperboard: Clapperboard,
  music: Music,
  gamepad: Gamepad2,
  "heart-pulse": HeartPulse,
  pill: Pill,
  dumbbell: Dumbbell,
  "graduation-cap": GraduationCap,
  book: Book,
  baby: Baby,
  "paw-print": PawPrint,
  wrench: Wrench,
  gift: Gift,
  package: Package,
  sparkles: Sparkles,
  briefcase: Briefcase,
  laptop: Laptop,
  "trending-up": TrendingUp,
  landmark: Landmark,
  coins: Coins,
  "hand-coins": HandCoins,
  banknote: Banknote,
  wallet: Wallet,
  "piggy-bank": PiggyBank,
  "credit-card": CreditCard,
  tag: Tag,
};

export const ICON_KEYS = Object.keys(CATEGORY_ICONS);
export const DEFAULT_ICON = "tag";

export function getCategoryIcon(key: string): LucideIcon {
  return CATEGORY_ICONS[key] ?? Tag;
}
